language: node_js
node_js:
  - 8
env:
  NODE_ENV = test
services: 
  mongodb
before_script:
  - sleep 15
  - npm install -g codecov
  - mongo test_db --eval 'db.createUser({username:"travis",passsword:"test", admin:true});'
scripts:
  npm test