language: node_js
node_js:
  - 8
env:
  process.env.NODE_ENV = 'ci'
services:
  mongodb
before_script:
  - sleep 15
  - npm install -g codecov
script:
  - npm test
  - codecov -t process.env.CODECOV_TOKEN
